apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tsm-manuell-api
  namespace: tsm
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        name: tsm-manuell-api-instance
        cascadingDelete: false
        databases:
          - name: tsm-manuell-api
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        pointInTimeRecovery: true
        tier: db-f1-micro
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 350Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  env:
    - name: GOSYS_OPPGAVE_URL
      value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver