apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tsm-manuell-api
  namespace: tsm
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 350Mi
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
