apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tsm-manuell-api
  namespace: tsm
spec:
  accessPolicy:
    outbound:
      rules:
        - application: syfosmmanuell-backend
          namespace: teamsykmelding
        - application: logging
          namespace: nais-system
    inbound:
      rules:
        - application: tsm-manuell
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        name: tsm-manuell-api-instance
        cascadingDelete: false
        databases:
          - name: tsm-manuell-api
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
          - name: cloudsql.enable_pgaudit
            value: "true"
        pointInTimeRecovery: true
        tier: db-f1-micro
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 150m
      memory: 750Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
  kafka:
    pool: nav-prod
  env:
    - name: GOSYS_OPPGAVE_URL
      value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver
    - name: TSM_PDL_ENDPOINT_URL
      value: http://tsm-pdl-cache
    - name: SYFOSMMANUELL_URL
      value: http://syfosmmanuell-backend.teamsykmelding
    - name: TEAMSYKEFRAVR_ISTILGANGSKONTROLL_URL
      value: http://istilgangskontroll.teamsykefravr
