spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          jwk-set-uri: ${AZURE_OPENID_CONFIG_JWKS_URI}
          audiences: ${AZURE_APP_CLIENT_ID}
      client:
        provider:
          aad:
            issuer-uri: ${azure.openid.config.issuer}
        registration:
          pdlcache-m2m:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            client-id: ${azure.app.client.id}
            client-secret: ${azure.app.client.secret}
            provider: aad
            scope:
              - ${tsmpdl.scope}
