-- -- MANUELLOPPGAVE table
-- CREATE TABLE manuelloppgave (
--     id VARCHAR PRIMARY KEY,
--     sykmeldingRecord JSONB NOT NULL,
--     validationresult JSONB NOT NULL,
--     pasientIdent CHAR(11) NOT NULL,
--     ferdigstilt BOOLEAN NOT NULL,
--     oppgaveid INTEGER,
--     opprinnelig_validationresult JSONB,
--     status VARCHAR,
--     status_timestamp TIMESTAMP WITH TIME ZONE
-- );
--
-- -- Indexes for MANUELLOPPGAVE
-- CREATE INDEX manuelloppgave_oppgaveid_idx ON manuelloppgave (oppgaveid);
-- CREATE INDEX manuelloppgave_sykmelding_id_index ON manuelloppgave ((sykmeldingRecord->'sykmelding'->>'id'));