name: Deploy app to dev and prod
on:
  push:
    branches:
      - '**'
permissions:
  actions: read
  contents: write
  security-events: write
  packages: write
  id-token: write

jobs:
  build:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/gradle-21.yaml@main
    secrets: inherit
    with:
      app: 'tsm-manuell-api'
